spring.datasource.url=jdbc:mysql://localhost:3306/cloudcostdb
spring.datasource.username=clouduser
spring.datasource.password=cloud123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
