apiVersion: apps/v1

kind: Deployment

metadata:
  name: cloud-cost-dashboard

spec:

  replicas: 2

  selector:
    matchLabels:
      app: cloud-cost-dashboard

  template:

    metadata:
      labels:
        app: cloud-cost-dashboard

    spec:

      containers:

      - name: cloud-cost-dashboard

        image: username/cloud-cost-dashboard:latest

        ports:

        - containerPort: 8080


