global:

 scrape_interval: 15s

scrape_configs:

 - job_name: cloud-cost-dashboard

   metrics_path: /actuator/prometheus

   static_configs:

   - targets:

     - cloud-cost-dashboard:8080


